version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    env_file: 
        - private-environment.txt
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      # In private-environment.txt
      #WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb

  db:
    image: mysql:5.7
    restart: always
    env_file: 
        - private-environment.txt
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      # In private-environment.txt
      #MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

